#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-expint
Version  : 0.1.8
Release  : 55
URL      : https://cran.r-project.org/src/contrib/expint_0.1-8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/expint_0.1-8.tar.gz
Summary  : Exponential Integral and Incomplete Gamma Function
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-expint-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Ei(x), and the incomplete gamma function G(a, x) defined for
  negative values of its first argument. The package also gives easy
  access to the underlying C routines through an API; see the package
  vignette for details. A test package included in sub-directory
  example_API provides an implementation. C routines derived from the

%package lib
Summary: lib components for the R-expint package.
Group: Libraries

%description lib
lib components for the R-expint package.


%prep
%setup -q -n expint
pushd ..
cp -a expint buildavx2
popd
pushd ..
cp -a expint buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737140505

%install
export SOURCE_DATE_EPOCH=1737140505
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/expint/CITATION
/usr/lib64/R/library/expint/DESCRIPTION
/usr/lib64/R/library/expint/INDEX
/usr/lib64/R/library/expint/Meta/Rd.rds
/usr/lib64/R/library/expint/Meta/features.rds
/usr/lib64/R/library/expint/Meta/hsearch.rds
/usr/lib64/R/library/expint/Meta/links.rds
/usr/lib64/R/library/expint/Meta/nsInfo.rds
/usr/lib64/R/library/expint/Meta/package.rds
/usr/lib64/R/library/expint/Meta/vignette.rds
/usr/lib64/R/library/expint/NAMESPACE
/usr/lib64/R/library/expint/NEWS.Rd
/usr/lib64/R/library/expint/R/expint
/usr/lib64/R/library/expint/R/expint.rdb
/usr/lib64/R/library/expint/R/expint.rdx
/usr/lib64/R/library/expint/doc/expint.R
/usr/lib64/R/library/expint/doc/expint.Rnw
/usr/lib64/R/library/expint/doc/expint.pdf
/usr/lib64/R/library/expint/doc/index.html
/usr/lib64/R/library/expint/example_API/DESCRIPTION
/usr/lib64/R/library/expint/example_API/NAMESPACE
/usr/lib64/R/library/expint/example_API/R/pkg.R
/usr/lib64/R/library/expint/example_API/man/pkg.Rd
/usr/lib64/R/library/expint/example_API/src/bar.c
/usr/lib64/R/library/expint/example_API/src/foo.c
/usr/lib64/R/library/expint/example_API/src/init.c
/usr/lib64/R/library/expint/example_API/src/locale.h
/usr/lib64/R/library/expint/example_API/src/pkg.h
/usr/lib64/R/library/expint/help/AnIndex
/usr/lib64/R/library/expint/help/aliases.rds
/usr/lib64/R/library/expint/help/expint.rdb
/usr/lib64/R/library/expint/help/expint.rdx
/usr/lib64/R/library/expint/help/paths.rds
/usr/lib64/R/library/expint/html/00Index.html
/usr/lib64/R/library/expint/html/R.css
/usr/lib64/R/library/expint/include/expintAPI.h
/usr/lib64/R/library/expint/tests/expint-tests.R
/usr/lib64/R/library/expint/tests/gammainc-tests.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/expint/libs/expint.so
/V4/usr/lib64/R/library/expint/libs/expint.so
/usr/lib64/R/library/expint/libs/expint.so
